baseURL = 'http://localhost:1313/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'kakeruhirokami.com'
theme = 'hugo-PaperMod'

[params]
  author = 'KakeruHirokami'